# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bbcd48b73b41639c393118cdc94bc4dd2066efdde9ea972c5877264886cb15f4964f91dcc2aeda528cac54809304a305a97558edde957b3c289665f778d3d4e0

test:
  secret_key_base: 17faf46763c2a096a035542bdf954fe4c8f6ddac64bd0f2d3ce4417182ddc7b1fb3f9ccb54b349ba7296648b2fea4210cf8eb709a4949200e57cab6c1582343c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
